#!/bin/bash
#
#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

#
# If this script doesn't work, you may need to add --user or --global
# to the "runhaskell Setup.hs configure" command below.
# It depends on where cabal has installed your packages, whether that
# was globally or just in your user home directory.
#
runhaskell Setup.hs configure --with-target=arm-qemu && \
  runhaskell Setup.hs build
