#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

DIRECTORIES += src/object

C_SOURCES += src/object/asyncendpoint.c src/object/cnode.c \
             src/object/endpoint.c src/object/interrupt.c \
             src/object/objecttype.c src/object/tcb.c \
             src/object/untyped.c
