#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#
DIRECTORIES += src/arch/arm/armv/${ARMV}

ARCH_ASM_SOURCES += armv/${ARMV}/machine_asm.S

ARCH_C_SOURCES += armv/${ARMV}/context_switch.c
ARCH_C_SOURCES += armv/${ARMV}/benchmark.c
ARCH_C_SOURCES += armv/${ARMV}/cache.c
