#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

DIRECTORIES += src/plat/exynos4/machine

PLAT_C_SOURCES += machine/hardware.c

PLAT_C_SOURCES += ../exynos_common/mct.c

ifdef DEBUG
    PLAT_C_SOURCES += machine/io.c
endif
