#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)
#

DIRECTORIES += src/plat/${PLAT}/machine

PLAT_C_SOURCES += machine/hardware.c       \
                  machine/l2cache.c        \
                  machine/intc.c           \
                  machine/io.c
