#
# Copyright 2016, CSIRO Data61
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(D61_GPL)
#

DIRECTORIES += src/plat/${PLAT}/machine

PLAT_C_SOURCES += machine/hardware.c       \
                  machine/l2cache.c        \
                  machine/intc.c           \
                  machine/io.c
