/*
 * Automatically generated C config: don't edit
 * project configuration
 * Mon Jun  6 11:31:20 2016
 */
#define AUTOCONF_INCLUDED
#define CONFIG_HAVE_ARCH_TIMER 1
#define CONFIG_USER_DEBUG_BUILD 1
#define CONFIG_ARM_HYPERVISOR_MODE 1
#define CONFIG_KERNEL_MASTER 1
#define CONFIG_EXPORT_PCNT_USER 1
#define CONFIG_TIMER_TICK_MS 2
#define CONFIG_KERNEL_CFLAGS ""
#define CONFIG_WORD_SIZE 32
#define CONFIG_MAX_NUM_BOOTINFO_DEVICE_REGIONS 200
#define CONFIG_MAX_NUM_TRACE_POINTS 0
#define CONFIG_VERIFICATION_BUILD 1
#define CONFIG_PLAT_TK1 1
#define CONFIG_FASTPATH 1
#define CONFIG_ARM_CORTEX_A15 1
#define CONFIG_EXPORT_VCNT_USER 1
#define CONFIG_LIB_SEL4_VKA_DEBUG_LIVE_OBJS_SZ 0
#define CONFIG_SEL4UTILS_CSPACE_SIZE_BITS 12
#define CONFIG_IPC_BUF_TPIDRURW 1
#define CONFIG_DOMAIN_SCHEDULE ""
#define CONFIG_CAMKES_SUPPORT_INIT 1
#define CONFIG_ARM_ERRATA_773022 1
#define CONFIG_ARM_HYPERVISOR_SUPPORT 1
#define CONFIG_ONDEMAND_DEVICE_INSTALL 1
#define CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS 50
#define CONFIG_CROSS_COMPILER_PREFIX "arm-linux-gnueabi-"
#define CONFIG_MAX_NUM_WORK_UNITS_PER_PREEMPTION 100
#define CONFIG_ARCH_ARM_V7A 1
#define CONFIG_OPTIMISATION_O2 1
#define CONFIG_ARCH_ARM 1
#define CONFIG_NUM_DOMAINS 16
#define CONFIG_RETYPE_FAN_OUT_LIMIT 256
#define CONFIG_ROOT_CNODE_SIZE_BITS 19
#define CONFIG_NUM_PRIORITIES 256
#define CONFIG_KERNEL_COMPILER ""
#define CONFIG_TIME_SLICE 5
#define CONFIG_ARCH_AARCH32 1
#define CONFIG_KERNEL_EXTRA_CPPFLAGS ""
#define CONFIG_ARM_MONITOR_HOOK 1
#define CONFIG_BUILDSYS_USE_CCACHE 1
#define CONFIG_MAX_NUM_NODES 1
#define CONFIG_KERNEL_STACK_BITS 12
