#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

ARCH_C_SOURCES += 32/kernel/vspace_32paging.c \
                  32/kernel/thread.c \
                  32/kernel/vspace.c \
                  32/kernel/elf.c
