#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#
DIRECTORIES += src/arch/arm/armv/${ARMV}/$(SEL4_ARCH)

ARCH_ASM_SOURCES += armv/${ARMV}/$(SEL4_ARCH)/machine_asm.S

ARCH_C_SOURCES += armv/${ARMV}/$(SEL4_ARCH)/benchmark.c
ARCH_C_SOURCES += armv/${ARMV}/$(SEL4_ARCH)/user_access.c
ARCH_C_SOURCES += armv/${ARMV}/$(SEL4_ARCH)/cache.c
