#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#
DIRECTORIES += src/arch/arm/armv/${ARMV}/$(TYPE_SUFFIX)

INCLUDE_DIRS += ${SOURCE_ROOT}/include/arch/arm/armv/${ARMV}/$(TYPE_SUFFIX)

ARCH_ASM_SOURCES += armv/${ARMV}/$(TYPE_SUFFIX)/machine_asm.S

ARCH_C_SOURCES += armv/${ARMV}/$(TYPE_SUFFIX)/benchmark.c
ARCH_C_SOURCES += armv/${ARMV}/$(TYPE_SUFFIX)/user_access.c
ARCH_C_SOURCES += armv/${ARMV}/$(TYPE_SUFFIX)/cache.c
