#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)
#

ARCH_C_SOURCES += 64/machine/hardware.c \
                  64/machine/registerset.c \
                  64/machine/fpu.c

ifdef DEBUG
    ARCH_C_SOURCES += 64/machine/capdl.c
endif
