#!/usr/bin/perl
#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

@args = @ARGV;

$ld = shift(@args);

map {s/^-Wl,//} @args;

exec $ld @args;
