#
# Copyright 2014, General Dynamics C4 Systems
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(GD_GPL)
#

include ${SOURCE_ROOT}/src/api/Makefile
include ${SOURCE_ROOT}/src/kernel/Makefile
include ${SOURCE_ROOT}/src/object/Makefile
include ${SOURCE_ROOT}/src/model/Makefile
include ${SOURCE_ROOT}/src/machine/Makefile

C_SOURCES += src/inlines.c \
             src/assert.c \
             src/util.c

