# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: License

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: License Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      uses: fsfe/reuse-action@master
